service: serenade-service

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-plugin-warmup
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'

  customDomain:
    certificateName: ${file(./serverless.env.yml):${self:provider.stage}.CERTIFICATE_NAME}
    domainName: ${file(./serverless.env.yml):${self:provider.stage}.DOMAIN_NAME}
    basePath: 'v1'
    stage: ${self:provider.stage}
    createRoute53Record: true

  warmup:
    default: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${file(./serverless.env.yml):${self:provider.stage}.AWS_REGION}
  profile: ${file(./serverless.env.yml):${self:provider.stage}.SERVERLESS_ADMIN}
  timeout: 30
  environment:
    REGION: ${self:provider.region}
    SENDGRID_API_KEY: ${file(./serverless.env.yml):${self:provider.stage}.SENDGRID_API_KEY}
    STAGE: ${self:provider.stage}
    DASHBOARD_URL: ${file(./serverless.env.yml):${self:provider.stage}.DASHBOARD_URL}
    POSTGRES_DB_HOST: ${file(./serverless.env.yml):${self:provider.stage}.POSTGRES_DB_HOST}
    POSTGRES_DB_NAME: ${file(./serverless.env.yml):${self:provider.stage}.POSTGRES_DB_NAME}
    POSTGRES_DB_USERNAME: ${file(./serverless.env.yml):${self:provider.stage}.POSTGRES_DB_USERNAME}
    POSTGRES_DB_PASSWORD: ${file(./serverless.env.yml):${self:provider.stage}.POSTGRES_DB_PASSWORD}
    SERENADE_SERVICE_API_KEY: ${file(./serverless.env.yml):${self:provider.stage}.SERENADE_SERVICE_API_KEY}
    JWT_SECRET: ${file(./serverless.env.yml):${self:provider.stage}.JWT_SECRET}
    API_URL: ${file(./serverless.env.yml):${self:provider.stage}.API_URL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
      - Fn::Join:
        - ':'
        - - arn:aws:lambda
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - function:${self:service}-${self:provider.stage}-*

functions:
  createUser:
    handler: app/functions/users/createUser.main
    events:
      - http:
          path: /users
          method: post
          cors: true

  deleteUser:
    handler: app/functions/users/deleteUser.main
    events:
      - http:
          path: /users/{userId}
          method: delete
          cors: true

  forgotUserPassword:
    handler: app/functions/users/forgotUserPassword.main
    events:
      - http:
          path: /users/password/forgot
          method: post
          cors: true

  getUser:
    handler: app/functions/users/getUser.main
    events:
      - http:
          path: /users/user
          method: get
          cors: true

  loginUser:
    handler: app/functions/users/loginUser.main
    events:
      - http:
          path: /users/login
          method: post
          cors: true

  resetUserPassword:
    handler: app/functions/users/resetUserPassword.main
    events:
      - http:
          path: /users/password/reset
          method: put
          cors: true

  updateUser:
    handler: app/functions/users/updateUser.main
    events:
      - http:
          path: /users/{userId}
          method: put
          cors: true
